# Generated by Django 4.0.3 on 2023-06-07 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snack', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='requester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snack',
            name='image',
            field=models.ImageField(upload_to='snack/images/'),
        ),
    ]
