# Generated by Django 4.0.3 on 2023-06-07 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0003_snack_requester_alter_snack_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.CharField(blank=True, help_text=' (개수 등 설명 추가)', max_length=300, verbose_name='DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='snack',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='IS_ACCEPTED'),
        ),
        migrations.AddField(
            model_name='snack',
            name='supply_month',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='SUPPLY_MONTH'),
        ),
        migrations.AddField(
            model_name='snack',
            name='supply_year',
            field=models.PositiveSmallIntegerField(default=2023, null=True, verbose_name='SUPPLY_YEAR'),
        ),
    ]
