# Generated by Django 4.0.3 on 2023-06-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0004_snack_description_snack_is_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='DESCRIPTION'),
        ),
    ]
