# Generated by Django 4.0.3 on 2023-06-21 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snack', '0005_alter_snack_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snack',
            options={'ordering': ['-vote_count']},
        ),
        migrations.AddField(
            model_name='snack',
            name='vote_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snack',
            name='voter',
            field=models.ManyToManyField(related_name='voter_snack', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snack',
            name='requester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requester_snack', to=settings.AUTH_USER_MODEL),
        ),
    ]
